export default [
    "Universitas Sebelas Maret",
    " Universitas Negeri Semarang",
    " Universitas Diponegoro",
    " Universitas Jenderal Soedirman",
    " Universitas Gadjah Mada",
    " Universitas Islam Negeri Walisongo",
    " Institut Seni Indonesia Surakarta",
    " Universitas Islam Indonesia",
    " Universitas Negeri Yogyakarta",
    " Universitas Tidar",
    " Universitas Muhammadiyah Surakarta",
    " Universitas Muhammadiyah Purwokerto",
    " Universitas Dian Nuswontoro",
    " Universitas Pembangunan Nasional Veteran Yogyakarta",
    " Universitas Wijaya Kusuma Purwokerto",
    " Universitas Ahmad Dahlan",

    " Universitas Padjadjaran",
    " Universitas Katolik Parahyangan",
    " Universitas Islam Bandung",
    " Universitas Pendidikan Indonesia",
    " Universitas Telkom",
    " Universitas Pasundan Bandung",
    " Politeknik Negeri Bandung",
    " Universitas Presiden",
    " Universitas Komputer Indonesia",
    " Universitas Jenderal Achmad Yani Bandung",
    " Institut Teknologi Nasional Bandung",
    " Universitas Islam Negeri Sunan Gunung Djati Bandung",
    " Universitas Widyatama",
    " Universitas Kristen Maranatha",
    " Sekolah Tinggi Hukum Bandung",
    " Sekolah Tinggi Ilmu Ekonomi Ekuitas Bandung",
    " Sekolah Tinggi Ilmu Ekonomi Indonesia Membangun",
    " Institut Teknologi Bandung",
    " Universitas Langlangbuana",
    " Politeknik Manufaktur Negeri Bandung",
    " Institut Seni Budaya Indonesia Bandung",
    " Universitas Siliwangi",
    " Institut Teknologi Harapan Bangsa",
    " Universitas Singaperbangsa Karawang",

    " Universitas Brawijaya",
    " Universitas Airlangga",
    " Universitas Pembangunan Nasional Veteran Jawa Timur",
    " Institut Teknologi Surabaya",
    " Universitas Negeri Surabaya",
    " Universitas Jember",
    " Politeknik Negeri Malang",
    " Universitas Islam Negeri Maulana Malik Ibrahim Malang",
    " Universitas Muhammadiyah Malang",
    " Universitas Negeri Malang",
    " Universitas Bina Nusantara Malang",
    " Universitas Merdeka Malang",
    " Universitas Ciputra",
    " Universitas Ma Chung",
    " Universitas Kristen Petra",
    " Institut Teknologi Nasional Malang",
    " Universitas Islam Malang",
    " Universitas Hang Tuah",
    " Universitas Islam Blitar",

    " Universitas Negeri Jakarta",
    " Universitas Trisakti",
    " Universitas Indonesia",
    " Universitas Tarumanegara",
    " Perbanas Institute (ABFI Institute Perbanas)",
    " Universitas Persada Indonesia Yayasan Administrasi Indonesia",
    " London School of Public Relation",
    " Universitas Bina Nusantara",
    " Universitas Pembangunan Nasional Veteran Jakarta",
    " Universitas Pelita Harapan",
    " Universitas Islam Negeri Syarif Hidayatullah Jakarta",
    " Universitas Muhammadiyah Jakarta",
    " Universitas Multimedia Nusantara",
    " Universitas Gunadarma",
    " Universitas Kristen Krida Wacana",
    " Institut Pertanian Bogor",
    " Bina Sarana Informatika",
    " Universitas Mercu Buana Jakarta",
    " Universitas Prasetiya Mulya",
    " Universitas Esa Unggul",
    " Universitas Pamulang",
    " Ppm School of Management",
    " Universitas Bunda Mulia",
    " Institut kesenian Jakarta",
    " Universitas Kristen Indonesia",
    " Universitas YARSI",

    " Universitas Udayana",
    " Universitas Warmadewa",
    " Universitas Pendidikan Nasional",
    " Universitas Pendidikan Ganesha",
    " Universitas Ngurah Rai",
    " Universitas Mahasaraswati Denpasar",
    " Institut Seni Indonesia Denpasar",
    " Politeknik Negeri Bali",
    " Sekolah Tinggi Manajemen Informatika dan Teknik Komputer Stikom Bali",
    " Universitas Bali Dwipa",
    " Universitas Mahendradatta",
    " Universitas Dwijendra"
];
